### ISSUE TITLE
missing tag 0.9.10

### ISSUE THREAD

**Issue by kuanyao** [expandjs/xp-adapter-behavior#1]
HI -
mat-icon has direct dependency on this behavior. It has been tagged as 0.9.10 and also expected 0.9.10 on this xp-adapter-behavior. Can you add a tag accordingly?

Thanks,
Kuan

**Comment by Pupix** [comment]
Hello!

I just did a clean install and the problem doesn't seem to pop up. You may be having a caching problem. Run `bower cache clean` and try to reinstall `mat-icon` afterwards.

Let me know how it goes. Cheers!

**Comment by kuanyao** [comment]
HI Robert -

I just did again and still getting the same error. If you look into mat-icon/bower.json you will see it has dependency on xp-adapter-behavior on 0.9.10, which does not exist yet. 

Not sure if this should be fixed from the mat-icon repo or on xp-adapter-behavior. Here is error:

bower not-cached    git://github.com/ExpandJS/xp-adapter-behavior.git#0.9.10
bower resolve       git://github.com/ExpandJS/xp-adapter-behavior.git#0.9.10
bower not-cached    git://github.com/ExpandJS/mat-icon.git#*
bower resolve       git://github.com/ExpandJS/mat-icon.git#*
bower download      https://github.com/ExpandJS/mat-icon/archive/v0.9.10.tar.gz
bower extract       mat-icon#\* archive.tar.gz
bower resolved      git://github.com/ExpandJS/mat-icon.git#0.9.10
bower ENORESTARGET  No tag found that was able to satisfy 0.9.10

Additional error details:
Available versions in git://github.com/ExpandJS/xp-adapter-behavior.git: 0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5, 0.9.4

Thanks,
Kuan

**Comment by kuanyao** [comment]
Also mat-icon wasn’t my first level dependency that I don’t have control on which version to use. 

Thanks,
Kuan

**Comment by Pupix** [comment]
What `mat-icon/bower.json` are you looking at?

We removed the `xp-adapter-behavior` dependency 2 weeks ago (https://github.com/expandjs/mat-icon/commit/ebd0e6b1bc4d0f8f9e517731e7dd4cf5439f9dce). There must be an outdated file in your `bower_components` folder, which causes the package manager to not download the new version correctly.

**Comment by kuanyao** [comment]
You are correct. After cleared all bower_components and rerun bower install everything looks fine now. 

There was a .bower.json (with dot in front) actually containing the older version. I had no idea of that file even exists.

Thanks for your help.

Regards,
Kuan

**Comment by Pupix** [comment]
Glad I could help.

Cheers,
Pupix
